dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/makara3.gemfile
services:
  - postgresql
script: bundle exec rake test
before_script:
  - createdb distribute_reads_test_primary
  - createdb distribute_reads_test_replica
notifications:
  email:
    on_success: never
    on_failure: change
